name: e2e-checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  SKIP_E2E_TAG: skip-e2e
  E2E_CHECK_NAME: e2e tests

jobs:
  e2e-checker:
    name: e2e-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: checker
        with:
          script: |
            let response = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: '${{ github.event.pull_request.head.sha }}',
              check_name: '${{ env.E2E_CHECK_NAME }}'
            });
            
            if (response.data.check_runs.length === 1){
              console.log("ID:")
              console.log(response.data.check_runs[0].id)
              
              await github.rest.checks.rerequestRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                check_run_id: response.data.check_runs[0].id,
              });

              
              return response.data.check_runs[0].id
            }else {
              console.log(response)
              return 0
            }

      - uses: LouisBrunner/checks-action@v1.1.1
        name: Enqueue e2e
        id: create
        if: "${{ steps.checker.outputs.result == 0 }}"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          name: ${{ env.E2E_CHECK_NAME }}
          status: queued
     
      - uses: LouisBrunner/checks-action@v1.1.1
        name: Skip e2e
        if:  ${{ contains(github.event.pull_request.labels.*.name, env.SKIP_E2E_TAG ) && steps.checker.outputs.result == 0 }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          check_id: ${{ steps.create.outputs.check_id }}
          conclusion: success
          output: |
            {"summary": "skipped by maintainer"}

      - uses: LouisBrunner/checks-action@v1.1.1
        name: Skip e2e
        if:  ${{ contains(github.event.pull_request.labels.*.name, env.SKIP_E2E_TAG ) && steps.checker.outputs.result > 0 }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          check_id: ${{ steps.checker.outputs.result }}
          conclusion: success
          output: |
            {"summary": "skipped by maintainer"}
