name: pr-e2e-tests
on:
  issue_comment:
    types: [created]

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Comment evaluate
    outputs:
      run-e2e: ${{ startsWith(github.event.comment.body,'/run-e2e') }}
      pr_num: ${{ steps.parser.outputs.pr_num }}
      image_tag: "pr-${{ steps.parser.outputs.pr_num }}-${{ steps.parser.outputs.commit_sha }}"
      commit_sha: ${{ steps.parser.outputs.commit_sha }}
    steps:
      - uses: actions/checkout@v3

      - name: Update comment with the execution url
        if: ${{ startsWith(github.event.comment.body,'/run-e2e')
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            **Update:** You can check the progres [here](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}})
          reactions: rocket

      - name: Parse git info
        if: ${{ startsWith(github.event.comment.body,'/run-e2e')
        id: parser
        run: |
          # Get PR number
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          echo "::set-output name=pr_num::$PR_NUM"
          # Get commit SHA
          git config --global --add safe.directory "$GITHUB_WORKSPACE"  
          gh pr checkout $PR_NUM         
          SHA=$(git log -n 1 --pretty=format:"%H")
          echo "::set-output name=commit_sha::$SHA"

      - name: Update status check
        uses: LouisBrunner/checks-action@v1.1.1
        if: ${{ startsWith(github.event.comment.body,'/run-e2e')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.parser.outputs.commit_sha }}
          name: e2e tests
          status: queued
          details_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}

  build-test-images:
    needs: triage
    runs-on: ubuntu-latest
    name: Build images
    container: ghcr.io/kedacore/build-tools:main
    if: needs.triage.outputs.run-e2e == 'true'
    steps:
      - name: Set status in-progress
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ needs.triage.outputs.commit_sha }}
          name: e2e tests
          status: in_progress

      - uses: actions/checkout@v3

  run-test:
    needs: [triage, build-test-images]
    runs-on: ubuntu-latest
    name: Execute e2e tests
    container: ghcr.io/kedacore/build-tools:main
    concurrency: pr-e2e-tests
    if: needs.triage.outputs.run-e2e == 'true'
    steps:
      - uses: actions/checkout@v3

      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: checkout
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          gh pr checkout ${{ needs.triage.outputs.pr_num }}


      - name: Set status success
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ needs.triage.outputs.commit_sha }}
          name: e2e tests
          conclusion: success
