name: e2e-checker
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

env:
  SKIP_E2E_TAG: skip-e2e

jobs:
  e2e-checker:
    name: e2e-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
           let response=await octokit.request('GET /repos/{owner}/{repo}/commits/{ref}/check-runs', {
              owner: ${{ github.repository.owner }},
              repo: ${{ github.repository }},
              ref: ${{ github.event.pull_request.head.sha }},
            })
           console.log(response)

      - uses: LouisBrunner/checks-action@v1.1.1
        name: Enqueue e2e
        #if: ${{ !contains(github.event.pull_request.labels.*.name, env.SKIP_E2E_TAG )}}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          name: e2e tests
          status: queued
      
      - uses: LouisBrunner/checks-action@v1.1.1
        name: Skip e2e
        if:  ${{ contains(github.event.pull_request.labels.*.name, env.SKIP_E2E_TAG )}}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha }}
          name: e2e tests
          conclusion: success
          output: |
            {"summary": "skipped by maintainer"}
